### PR TITLE
Adding configurable staging repository description

### PR DESCRIPTION
**Pull request by akomakom**
my company relies on staging repository description for various cleanup jobs, so blindly setting them to "Automatically released/promoted with gradle-nexus-staging-plugin!" isn't always ideal.

I didn't add any tests because I couldn't figure out how to test this with wiremock - the best I could do was verify that the RepositoryCloser instance had the right description set in its field (which seemed kind of weak), so I didn't include that in this PR.  Suggestions are welcome.

### CODE REVIEW

**Comment by akomakom** [comment]
Test failures appear to be environment-related, not up to me to fix.

**Comment by szpak** [comment]
@akomakom Thanks for your contribution. I merged it manually and slightly refactored. It's available in just automatically released version [0.10.0](https://github.com/Codearte/gradle-nexus-staging-plugin/releases).

Btw, I will leave this PR open for a time being to try to find a workaround for the issue with PGP key not available in PR builds on Travis.

**Comment by szpak** [comment]
Btw, add your email address you used in the [commit](https://github.com/Codearte/gradle-nexus-staging-plugin/commit/f32c572b3e545d02d3a1bb5bbd9e041f8c56c376) to your GitHub account to be listed on the [contributors page](https://github.com/Codearte/gradle-nexus-staging-plugin/graphs/contributors).

**Comment by akomakom** [comment]
@szpak thanks for bringing this to my attention, I had user.email set all wrong on my 200 random work/non-work related repositories.

**Pull request closed without merging**
